spring:
  datasource:
    url: jdbc:postgresql://database:5432/restaurant
    password: restaurant
    username: restaurant
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: mailcatcher
    port: 1025
    username: no-reply@restaurant.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

security:
  refresh-token:
    validity-time: 259200
    secret: secret-refresh123!
  access-token:
    validity-time: 1800
    secret: secret-access123!
  cors:
    allowed-methods: GET,POST,PUT.PATCH,DELETE,ORIGIN
    allowed-headers: "*"
    allowed-origins: http://localhost:3000
