spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/restaurant
    password: restaurant
    username: restaurant
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    validity-time: 60
    secret: secret123dasd!
  cors:
    allowed-methods: GET,POST,PUT.PATCH,DELETE,ORIGIN
    allowed-headers: "*"
    allowed-origins: http://localhost:3000