spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/restaurant
    password: restaurant
    username: restaurant
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


security:
  refresh-token:
    validity-time: 259200
    secret: secret-refresh123!
  access-token:
    validity-time: 1800
    secret: secret-access123!
  cors:
    allowed-methods: GET,POST,PUT.PATCH,DELETE,ORIGIN
    allowed-headers: "*"
    allowed-origins: http://localhost:3000